require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/collections", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Collection. As you add validations to Collection, be sure to
  # adjust the attributes here as well.
  let(:current_admin) { create(:user_admin) }
  let(:valid_attributes) {
    {
      name: "My Collection",
      equations_quantity: 2,
      user_admin_id: current_admin.id
    }
  }

  let(:invalid_attributes) {
    {
      name: nil,  # Invalid because name is required
      equations_quantity: -1,  # Invalid because equations_quantity should be a positive integer
      user_admin_id: nil  # Invalid because user_admin_id is required
    }
  }

  before(:each) do
    sign_in current_admin
  end

  describe "GET /index" do
    it "renders a successful response" do
      Collection.create! valid_attributes
      get collections_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      collection = Collection.create! valid_attributes
      get collection_url(collection)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_collection_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      collection = Collection.create! valid_attributes
      get edit_collection_url(collection)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Collection" do
        expect {
          post collections_url, params: { collection: valid_attributes }
        }.to change(Collection, :count).by(1)
      end

      it "redirects to the created collection" do
        post collections_url, params: { collection: valid_attributes }
        expect(response).to redirect_to(collection_url(Collection.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Collection" do
        expect {
          post collections_url, params: { collection: invalid_attributes }
        }.to change(Collection, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post collections_url, params: { collection: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        {
          name: "Sample Collection",
          equations_quantity: 5,
          user_admin: current_admin
        }
      }

      it "updates the requested collection" do
        collection = Collection.create! valid_attributes
        patch collection_url(collection), params: { collection: new_attributes }
        collection.reload
        expect(collection.name).to eq("Sample Collection")
        expect(collection.equations_quantity).to eq(5)
        expect(collection.user_admin).to eq(new_attributes[:user_admin])
      end

      it "redirects to the collection" do
        collection = Collection.create! valid_attributes
        patch collection_url(collection), params: { collection: new_attributes }
        collection.reload
        expect(response).to redirect_to(collection_url(collection))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        collection = Collection.create! valid_attributes
        patch collection_url(collection), params: { collection: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested collection" do
      collection = Collection.create! valid_attributes
      expect {
        delete collection_url(collection)
      }.to change(Collection, :count).by(-1)
    end

    it "redirects to the collections list" do
      collection = Collection.create! valid_attributes
      delete collection_url(collection)
      expect(response).to redirect_to(collections_url)
    end
  end
end
