require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/equations", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Equation. As you add validations to Equation, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Equation.create! valid_attributes
      get equations_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      equation = Equation.create! valid_attributes
      get equation_url(equation)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_equation_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      equation = Equation.create! valid_attributes
      get edit_equation_url(equation)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Equation" do
        expect {
          post equations_url, params: { equation: valid_attributes }
        }.to change(Equation, :count).by(1)
      end

      it "redirects to the created equation" do
        post equations_url, params: { equation: valid_attributes }
        expect(response).to redirect_to(equation_url(Equation.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Equation" do
        expect {
          post equations_url, params: { equation: invalid_attributes }
        }.to change(Equation, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post equations_url, params: { equation: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested equation" do
        equation = Equation.create! valid_attributes
        patch equation_url(equation), params: { equation: new_attributes }
        equation.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the equation" do
        equation = Equation.create! valid_attributes
        patch equation_url(equation), params: { equation: new_attributes }
        equation.reload
        expect(response).to redirect_to(equation_url(equation))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        equation = Equation.create! valid_attributes
        patch equation_url(equation), params: { equation: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested equation" do
      equation = Equation.create! valid_attributes
      expect {
        delete equation_url(equation)
      }.to change(Equation, :count).by(-1)
    end

    it "redirects to the equations list" do
      equation = Equation.create! valid_attributes
      delete equation_url(equation)
      expect(response).to redirect_to(equations_url)
    end
  end
end
