require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/equations", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Equation. As you add validations to Equation, be sure to
  # adjust the attributes here as well.
  let(:current_admin) { create(:user_admin) }

  before(:each) do
    sign_in current_admin
  end

  let(:valid_attributes) {
    {
      position_a: 1,
      position_b: 2,
      position_c: 3,
      operator: '+',
      unknown_position: 'a',
      user_admin_id: current_admin.id
    }
  }

  let(:invalid_attributes) {
    {
      position_a: nil,  # Invalid because position_a is required
      position_b: nil,  # Invalid because position_b is required
      position_c: nil,  # Invalid because position_c is required
      operator: nil,    # Invalid because operator is required
      unknown_position: nil,  # Invalid because unknown_position is required
      user_admin_id: nil  # Invalid because user_admin_id is required
    }
  }

  describe "GET /index" do
    it "renders a successful response" do
      Equation.create! valid_attributes
      get equations_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      equation = Equation.create! valid_attributes
      get equation_url(equation)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_equation_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      equation = Equation.create! valid_attributes
      get edit_equation_url(equation)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Equation" do
        expect {
          post equations_url, params: { equation: valid_attributes }
        }.to change(Equation, :count).by(1)
      end

      it "redirects to the created equation" do
        post equations_url, params: { equation: valid_attributes }
        expect(response).to redirect_to(equation_url(Equation.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Equation" do
        expect {
          post equations_url, params: { equation: invalid_attributes }
        }.to change(Equation, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post equations_url, params: { equation: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        {
          position_a: 3,
          position_b: 2,
          position_c: 5,
          operator: "+",
          unknown_position: "b",
          user_admin_id: current_admin.id
        }
      }

      it "updates the requested equation" do
        equation = Equation.create! valid_attributes
        patch equation_url(equation), params: { equation: new_attributes }
        equation.reload
        expect(equation.position_a).to eq(new_attributes[:position_a])
        expect(equation.position_b).to eq(new_attributes[:position_b])
        expect(equation.position_c).to eq(new_attributes[:position_c])
        expect(equation.operator).to eq(new_attributes[:operator])
        expect(equation.unknown_position).to eq(new_attributes[:unknown_position])
        expect(equation.user_admin_id).to eq(new_attributes[:user_admin_id])
      end

      it "redirects to the equation" do
        equation = Equation.create! valid_attributes
        patch equation_url(equation), params: { equation: new_attributes }
        equation.reload
        expect(response).to redirect_to(equation_url(equation))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        equation = Equation.create! valid_attributes
        patch equation_url(equation), params: { equation: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested equation" do
      equation = Equation.create! valid_attributes
      expect {
        delete equation_url(equation)
      }.to change(Equation, :count).by(-1)
    end

    it "redirects to the equations list" do
      equation = Equation.create! valid_attributes
      delete equation_url(equation)
      expect(response).to redirect_to(equations_url)
    end
  end
end
