require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/groupings", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Grouping. As you add validations to Grouping, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Grouping.create! valid_attributes
      get groupings_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      grouping = Grouping.create! valid_attributes
      get grouping_url(grouping)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_grouping_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      grouping = Grouping.create! valid_attributes
      get edit_grouping_url(grouping)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Grouping" do
        expect {
          post groupings_url, params: { grouping: valid_attributes }
        }.to change(Grouping, :count).by(1)
      end

      it "redirects to the created grouping" do
        post groupings_url, params: { grouping: valid_attributes }
        expect(response).to redirect_to(grouping_url(Grouping.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Grouping" do
        expect {
          post groupings_url, params: { grouping: invalid_attributes }
        }.to change(Grouping, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post groupings_url, params: { grouping: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested grouping" do
        grouping = Grouping.create! valid_attributes
        patch grouping_url(grouping), params: { grouping: new_attributes }
        grouping.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the grouping" do
        grouping = Grouping.create! valid_attributes
        patch grouping_url(grouping), params: { grouping: new_attributes }
        grouping.reload
        expect(response).to redirect_to(grouping_url(grouping))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        grouping = Grouping.create! valid_attributes
        patch grouping_url(grouping), params: { grouping: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested grouping" do
      grouping = Grouping.create! valid_attributes
      expect {
        delete grouping_url(grouping)
      }.to change(Grouping, :count).by(-1)
    end

    it "redirects to the groupings list" do
      grouping = Grouping.create! valid_attributes
      delete grouping_url(grouping)
      expect(response).to redirect_to(groupings_url)
    end
  end
end
